package:
    type:           yii2-extension
    name:           yii2-theme-original
    title:          Yii2 Original Theme for Yii2 projects
    headline:       Yii2 Original Theme
    keywords:       yii2, original, theme, plugin
    description:    |
        This package provides Yii2 original theme for Yii2 projects.

        This package uses [hiqdev/yii2-thememanager] theming library.

        [hiqdev/yii2-thememanager]: https://github.com/hiqdev/yii2-thememanager
